### ISSUE TITLE
[Feature]: press `<CR>` on lines in the summary window to jump to the matching test

### ISSUE THREAD

**Issue by mrjones2014** [nvim-neotest/neotest#101]
`require('neotest').summary.open()` is really cool. 

It would be even cooler if pressing `<CR>` on a test name would jump your cursor to that test in the main buffer.

**Comment by hahuang65** [comment]
Currently, you can press `i` to jump to the test under your cursor.

**Comment by mrjones2014** [comment]
Oh cool, is there any configuration option to remap the key? If I can configure it then we can close this issue, otherwise can we repurpose this issue into making that key configurable?

**Comment by hahuang65** [comment]
@mrjones2014 Looks like it: https://github.com/nvim-neotest/neotest/blob/master/doc/neotest.txt#L137
But note that `<CR>` is already bound by default to `expand` (when the summary folds up sections of tests), so you'll probably want to re-bind that was well.

**Comment by mrjones2014** [comment]
Perfect, thanks!
