### ISSUE TITLE
[BUG] Test files without tests cause infinite "progress" state

### ISSUE THREAD

**Issue by tomhampshire** [nvim-neotest/neotest#103]
**NeoVim Version**
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3

**Describe the bug**
Note: this applies to a Python project. I am unable to test with other language(s), so this might be an issue with neotest-python.
When running a full test suite (the project uses pytest) by opening the test summary window `lua require("neotest").summary.toggle()`, selecting the root node of the project and pressing `r`, if there exists a `test_something.py` file that has functions, but no tests inside, the test's status for that file will remain as in-progress indefinitely.

**Expected behavior**
The test should show another status, rather than "in-progress" for the test file with the missing tests.

**Comment by rcarriga** [comment]
This shouldn't be happening AFAIK. Can you check if the process completes by trying to attach? If it can't attach then something strange is going on in the result aggregation and so I'll need to do more digging

**Comment by tomhampshire** [comment]
I now cannot recreate the problem. I'm doing exactly the same set of tests and it's running fine - the file without any tests now sets the status to ø rather than remaining in an "in-progress" state. I've updated all of my plugins via packer today, though, so I can't recreate the same environment. Either way, I think my original bug report can be ignored. Thanks for looking into it.

**Comment by rcarriga** [comment]
Please open a separate issue with a bug report so I can reproduce
