### ISSUE TITLE
C# Tests fail (language issue?)

### ISSUE THREAD

**Issue by Nekketsu** [nvim-neotest/neotest#116]
When I run C# tests, it says that they are all incorrect.

If I show the output, it says that the tests are correct.
Could it be a language issue? `dotnet` is showing the results in Spanish.

![image](https://user-images.githubusercontent.com/2674336/191956644-df33412f-edfe-4564-9ebd-60b67bc7f599.png)

**Comment by rcarriga** [comment]
I'm not sure what the problem is as this is an adapter specific issue and I don't maintain it. Please open an issue in the neotest-dotnet repo
