### ISSUE TITLE
Feature request: Select subset of tests to execute

### ISSUE THREAD

**Issue by stehessel** [nvim-neotest/neotest#12]
It would be cool if there was a way to mark tests for execution - for example via a toggle in the summary window - and then run them with a command like `run.run_selected()`. This would increase the flexibility of test execution.

**Comment by stehessel** [comment]
The use case I envision would be:

* You are working on code in file A.
* The code changes affect code in files B and C.
* You want to run testB1, testB2 and testC5 while iterating on your changes in file A.

This is not about performance. How the tests are executed and whether they are run concurrently would be an implementation detail, you could also execute the tests serially in a single thread. It's about running the tests you want to run, even when they are scattered in different files.

**Comment by stehessel** [comment]
One corner case would be parametrized tests - e.g. using pytest. If I remember correctly PyCharm treats parameters as separate tests and allows to select individual selection for them. I think that's ideal, but it might be easier to select only based on test and file names and then run all parameters.

**Comment by rcarriga** [comment]
OK that all makes sense, just wanted to make sure I understood the need properly :+1: 

> If I remember correctly PyCharm treats parameters as separate tests and allows to select individual selection for them

That'd be a feature request for neotest-python to detect them as separate tests but that sounds very cool

**Comment by rcarriga** [comment]
OK I've added the ability to mark tests in the summary and run them. See `:h neotest.summary.run_marked()` and `:h neotest.Config.summary.mappings` for details

**Comment by stehessel** [comment]
Awesome, thank you!
