### ISSUE TITLE
[Feature Request] Hide/collapse directories

### ISSUE THREAD

**Issue by CallumHoward** [nvim-neotest/neotest#121]
I would like an option to hide directories in the Summary window, or at least collapse directories into a single line like in `vim-ultest`.

<img width="233" alt="Screen Shot 2022-10-02 at 10 56 25 am" src="https://user-images.githubusercontent.com/7144420/193432348-52d512d3-dfcb-4628-a230-504b37df9e02.png">

For context, I have the setting for

```lua
discovery = {
  enabled = false,
},
```

...and my Summary window looks something like this:
<img width="229" alt="Screen Shot 2022-10-02 at 10 48 03 am" src="https://user-images.githubusercontent.com/7144420/193432297-1a02a995-7116-4daa-ab84-414d9d498213.png">

**Comment by rcarriga** [comment]
You can already collapse directories with the `expand` mapping. They may auto-expand again if you have the `follow` setting enabled. You may also want to check out the `target` mapping which allows you to only see a specific position

**Comment by CallumHoward** [comment]
Thanks! I tried out `target` and that gets me pretty close to what I'm after, which is working with tests in deeply nested directories.

Some thoughts for possible future features:
- Target marked (allowing multiple targets)
- Target/auto-target given or current open file/files

I'll close the issue for now though, thanks again!
