### ISSUE TITLE
Send results to quickfix/location list

### ISSUE THREAD

**Issue by weeman1337** [nvim-neotest/neotest#133]
Use case

It would be handy if failed tests could be sent to the quickfix or location list.
This way I could easily jump to each failed test.

**Comment by haringsrob** [comment]
With https://github.com/nvim-neotest/neotest/pull/177 I think there's a regression that it cannot be disabled?

```lua
        require('neotest-phpunit')({
            consumers = {
                quickfix = {
                    open = false,
                    enabled = false,
                },
            },
            quickfix = {
                open = false,
                enabled = false,
            },
```

Quickfix always opens on test failure with the config above. (or without it)

**Comment by rcarriga** [comment]
You're configuring `neotest-phpunit` not `neotest` in that snippet :smile: 
```lua
        require('neotest')({
            quickfix = {
                open = false,
            },
```

**Comment by weeman1337** [comment]
Yeah - closed by https://github.com/nvim-neotest/neotest/pull/177
