### ISSUE TITLE
How to define a key to quit output window.

### ISSUE THREAD

**Issue by scottming** [nvim-neotest/neotest#138]
This floating window is a non-editable window, so I think we can set `q` as a quit key instead of `:q`, just like [lspsaga](https://github.com/glepnir/lspsaga.nvim), `definition` and `finder` can be quit with `q`.

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/12830256/199675499-c99a22c2-e787-4c13-951d-642885ce0520.png">

**Comment by rcarriga** [comment]
You can define an autocmd to do this
```lua
  local group = vim.api.nvim_create_augroup("NeotestConfig", {})
  vim.api.nvim_create_autocmd("FileType", {
    pattern = "neotest-output",
    group = group,
    callback = function(opts)
      vim.keymap.set("n", "q", function()
        pcall(vim.api.nvim_win_close, 0, true)
      end, {
        buffer = opts.buf,
      })
    end,
  })

```

**Comment by scottming** [comment]
Thank you, it works, and this plugin is really cool.

**Comment by gegnew** [comment]
except for the attach window, which is editable, and apparently it cannot be exited unless I click outside of it...?

**Comment by rcarriga** [comment]
I've set the filetype for the attach window to `neotest-attach` so you can do the same for it too

**Comment by gegnew** [comment]
Apologies for not following up on this earlier, but afaict this doesn't work for the attach window. For instance, if I use `pdb` inside a test that I run with `neotest`, then attach the test, then continue through the test ("c" in the `pdb` shell in the attached window), everything freezes. I can't run any commands, navigate, nothing at all. The only option is to click outside the attach window, whereupon the attach window closes and everything is fine.

**Comment by rcarriga** [comment]
The attach window is a terminal window, so when you enter insert mode you're actually in terminal mode. You're getting stuck because all keys except `<C-\><C-n>` are sent to PDB. See `:h Terminal-mode`. You can set keymappings for terminal mode with `tnoremap`
