### ISSUE TITLE
[BUG] Failed test diagnostics don't get shown immediately, but only after saving the file. (Due to inconsistent path slash usage -> `\` and `/`)

### ISSUE THREAD

**Issue by DasOhmoff** [nvim-neotest/neotest#141]
Hey 👋, thanks again for this great plugin.

On my machine, when a test fails, the diagnostics for it do not get shown immediately. But only after I do some action, for example, saving the file. I looked through the source code and I think I found the issue. It seems to be in here:
https://github.com/nvim-neotest/neotest/blob/604dd922ad461f08048010505b7056f613b4d478/lua/neotest/consumers/diagnostic.lua#L191-L214

At these lines, the buffer paths get saved:
https://github.com/nvim-neotest/neotest/blob/604dd922ad461f08048010505b7056f613b4d478/lua/neotest/consumers/diagnostic.lua#L200-L203

And here they get checked:
https://github.com/nvim-neotest/neotest/blob/604dd922ad461f08048010505b7056f613b4d478/lua/neotest/consumers/diagnostic.lua#L207-L209

The issue is that `valid_bufs` and `node:data().path` have different ways of storing slashes. Example of printing these variables on my machine:

`valid_bufs`:
```
{
  ["C:\\Users\\X/MyStuff/Programming/Business/X/frontend/src/app/sign-up-form/login-form.component.spec.ts"] = true,
}
```

`node:data().path`:
```
C:\\Users\\X\\MyStuff\\Programming\\Business\\X\\frontend\\src\\app\\sign-up-form\\login-form.component.spec.ts
```
Because of that, the if check does not succeed, and the buffer does not get redrawn with the symbols. I would be nice to fix this.

Also, I think it is worth it to see if the same thing is also done in other parts of the code, maybe there is the same issue at other places.

Thank you for your help! :)

**Comment by rcarriga** [comment]
Thanks for the report, could you please try the latest commit? Don't have windows so can't confirm but think this should be fixed

**Comment by DasOhmoff** [comment]
It seems to work perfectly! Thanks :)
