### ISSUE TITLE
[Feature] How to run the test in an Interactive shell and collect the result?

### ISSUE THREAD

**Issue by scottming** [nvim-neotest/neotest#162]
Thank you so much for your work, this plugin is really great. I mainly use Elixir to develop web projects for my daily work, Elixir is a language built based on the erlang Beam virtual machine, and it's a great experience for building web applications. 

But running tests with `mix test` in a UNIX shell is very slow(2-3seconds) because of the startup, which is causing **TDD** to be a pain. I've already found a way to run the tests in iex (an interactive shell that is similar to `ipython` for `python` language), which eliminates the startup step, and for some tests, this way can boost the speed by **100x**.

But I'm not familiar with neovim, so I'm having some problems with how to start the iex shell when neotest starts. And how do I send commands to the shell to collect results on run `require("neotest").run.run()`? Also, I noticed that neotest already has `output_panel`, I wonder if the iex shell can run in it?

FYI, here is a small video I recorded, I am currently using toggleterm to send my startup commands and test commands, but I would prefer I could integrate neotest, I hope you can give me some advice and direction.

https://user-images.githubusercontent.com/12830256/202839889-48f2aef6-3568-4c21-b36f-3062e105ec03.mp4

In the video above, you can see that test with neotest is very slow because the `mix test` is used here, While the second half is very fast and almost instantaneous, I used the following two commands

```lua
-- start the iex interactive shell
vim.api.nvim_create_user_command("TestIexStart", function()
	toggleterm.exec('MIX_ENV=test iex --no-pry -S mix run -e "TestIex.start()"', 1)
	--[[ ttt.get_or_create_term(1):close() ]]
end, {})

-- send the testifle and line to the iex shell 
vim.api.nvim_create_user_command("TestIex", function()
	local line_col = vim.api.nvim_win_get_cursor(0)[1]
	local path = vim.fn.expand("%")
	toggleterm.exec(string.format("TestIex.test(%q, %q)", path, line_col), 1)
end, {})
```

I've asked this question [here](https://github.com/jfpedroza/neotest-elixir/issues/12) as well, but I think it might be more appropriate to put the question here.

**Comment by rcarriga** [comment]
Continuing conversation in linked thread to keep it all in one place :smile:

**Comment by rcarriga** [comment]
As this seems to be able to be completely handled by the adapter, I'm going to close this
