### ISSUE TITLE
Project-local settings should override global settings

### ISSUE THREAD

**Issue by MisanthropicBit** [nvim-neotest/neotest#175]
I'm working on a couple of js/ts repos where both mocha and jest are used. In my setup I use:

```lua
neotest.setup{
  ...
  adapters = {
    require('neotest-jest')({
        jestCommand = 'npm test --runInBand --',
        jestConfigFile = 'jest.config.ts',
        cwd = get_cwd,
    }),
    require('neotest-mocha')({
        command = 'npm test --',
        cwd = get_cwd,
    }),
    require("neotest-vim-test")({}),
  }
}

neotest.setup_project('~/path/to/project', {
  ...
  adapters = {
    require('neotest-mocha')({
        command = 'npm test --',
        cwd = get_cwd,
    }),
  }
})
```

Since I have a specific project where I want to use only mocha. However, I'm running into the same issue as reported in #105 if I open a test file in the project directory where both neotest-jest and neotest-mocha load and neotest-jest takes priority seemingly due to the ordering in the global setup.

While related to #105, I would have expected neotest to only use neotest-mocha here but it seems that the behavior is more like merging the two configs?

Is my setup wrong? If not, it would be great to have an `override_adapters` option to tell neotest to ignore global adapters for project setups.

Otherwise, a solution to #105 would also solve this one although not the underlying issue with project-specific setups. And thanks for this great plugin 🙂 (I didn't tag this as a bug since I'm not sure that it is one). I would be happy to submit a PR if needed.

**Comment by rcarriga** [comment]
The expected behaviour is for only the mocha adapter to be used. Can you provide the info requested in the bug report template so that I can reproduce?

**Comment by MisanthropicBit** [comment]
Thanks for confirming the expected behaviour :) I'll provide the bug info.

**Comment by scottming** [comment]
yes, I have the same problem, I use 

```
neotest.setup_project(vim.loop.cwd(), {
	adapters = { require("neotest-elixir") },
	default_strategy = "iex",
})
```
can't override the default_strategy.

**Comment by rcarriga** [comment]
The default strategy should now be fixed :+1:

**Comment by MisanthropicBit** [comment]
I've had time to test this out a bit more and I cannot reproduce the issue with the example setup in the bug template so the problem must be something with my setup. Apologies.
