### ISSUE TITLE
Configure Neotest Summary Width

### ISSUE THREAD

**Issue by harrisoncramer** [nvim-neotest/neotest#178]
Hello, thank you for the awesome plugin!

Is the width of the summary panel configurable? It's a bit narrow on my monitor, and I'm not seeing any options in the API for configuring a default width.

**Comment by rcarriga** [comment]
You can now specify an `open` option in the summary config. The default value is `botright vsplit | vertical resize 50`, so you can just change the `50` to whatever width you like

**Comment by harrisoncramer** [comment]
Awesome, thank you!
