### ISSUE TITLE
[BUG] No tests found under windows

### ISSUE THREAD

**Issue by Perry3D** [nvim-neotest/neotest#188]
**NeoVim Version**
```
nvim --version
NVIM v0.8.2
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Übersetzt von runneradmin@fv-az28-353

Features: -acl +iconv +tui
See ":help feature-compile"

          System-vimrc-Datei: "$VIM\sysinit.vim"
     Voreinstellung für $VIM: "C:/Program Files (x86)/nvim/share/nvim"

Run :checkhealth for more info
```

**Describe the bug**
I am using neotest with neotest-python. 

***Windows***
When using it under Windows 10 i get the message "No tests found". In the log file this one appears:
```
ERROR | 2023-01-03T14:06:38Z+0100 | ...Local\nvim-data\lazy\neotest/lua/neotest/client/init.lua:309 | Couldn't find positions in path D:\PoeTrader\tests\test_messages.py ...cal\nvim-data\lazy\neotest/lua/neotest/lib/file/find.lua:26: ENOTDIR: not a directory: D:\PoeTrader\tests\test_messages.py
stack traceback:
	[C]: in function 'assert'
	...cal\nvim-data\lazy\neotest/lua/neotest/lib/file/find.lua:26: in function 'find'
	...Local\nvim-data\lazy\neotest/lua/neotest/client/init.lua:284: in function <...Local\nvim-data\lazy\neotest/lua/neotest/client/init.lua:264>
	[C]: in function 'xpcall'
	...Local\nvim-data\lazy\neotest/lua/neotest/client/init.lua:264: in function '_update_positions'
	...Local\nvim-data\lazy\neotest/lua/neotest/client/init.lua:317: in function <...Local\nvim-data\lazy\neotest/lua/neotest/client/init.lua:315>
```
Opening the summary windows shows the test files but without the tests:
![image](https://user-images.githubusercontent.com/986287/210375896-d20fcd64-8ca1-4161-be01-35d2550124a1.png)

***WSL***
I tried the same neovim config and the same application under WSL and everything seems to work fine:
![image](https://user-images.githubusercontent.com/986287/210376032-fe6ea4d8-9f1e-4beb-a941-51a2d6b21639.png)

My neotest config can be found here: https://git.freiewildbahn.de/oli/nvim/src/commit/e3c8a5ddd446aacbb0631af95c28baf0fe5635de/lua/plugins/neotest.lua

The python source code i used for testing:  https://git.freiewildbahn.de/oli/PoeTrade/src/commit/07008d2e08f152bbd2141ee8cd0f9c0d565c0055

I try to provide a minimal example later.

**Comment by rcarriga** [comment]
Sorry I don't have a windows machine to test on but AFAICT for some reason the file is being detected as a directory ([here](https://github.com/nvim-neotest/neotest/blob/414b43f99da0a827c3ce897161fc67c3bb6a5d83/lua/neotest/client/init.lua#L265)) and so trying to be searched. Could you check what `print(require("neotest.lib").files.is_dir("D:\\PoeTrader\\tests\\test_messages.py"))` prints?

**Comment by Perry3D** [comment]
**Windows**
Output from `:lua print(require("neotest.lib").files.is_dir("D:\\PoeTrader\\tests\\test_messages.py"))` is `true nil`

**WSL**
Something silimiar under WSL `:lua print(require("neotest.lib").files.is_dir("/mnt/d/PoeTrader/tests/test_messages.py"))` gives `nil /mnt/d/PoeTrader/tests/test_messages.py/: Not a directory`

**Comment by Perry3D** [comment]
I have no experience with plugin development. But why don't you use `vim.fn.isdirectory`?

`:lua print(vim.fn.isdirectory('D:\\PoeTrader\\tests\\test_messages.py'))` returns 0 and
`:lua print(vim.fn.isdirectory('D:\\PoeTrader\\tests'))` returns 1

**Comment by rcarriga** [comment]
I've switched to using `isdirectory` :smile: Let me know if there are any other issues!

**Comment by schester44** [comment]
similar error for me

stack traceback:
        [C]: in function 'assert'
        ...l/share/nvim/lazy/neotest/lua/neotest/lib/subprocess.lua:147: in function 'call'
        ...re/nvim/lazy/neotest/lua/neotest/lib/treesitter/init.lua:189: in function 'discover_positions'
        ...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:300: in function <...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:264>
        [C]: in function 'xpcall'
        ...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:264: in function '_update_positions'
        ...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:317: in function <...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:315>
ERROR | 2025-03-07T12:08:53Z-0500 | ...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:309 | Couldn't find positions in path /Users/schester/work/risk-management/web-client/src/lib/getClientQuoteRequestStatus.test.ts ...l/share/nvim/lazy/neotest/lua/neotest/lib/subprocess.lua:147: Invalid subprocess call: Vim:Error invoking 'nv
