### ISSUE TITLE
Attach window freezes neovim

### ISSUE THREAD

**Issue by gegnew** [nvim-neotest/neotest#189]
Apologies for not following up on this earlier, but afaict this doesn't work for the attach window. For instance, if I use `pdb` inside a test that I run with `neotest`, then attach the test, then continue through the test ("c" in the `pdb` shell in the attached window), everything freezes. I can't run any commands, navigate, nothing at all. The only option is to click outside the attach window, whereupon the attach window closes and everything is fine.

_Originally posted by @gegnew in https://github.com/nvim-neotest/neotest/issues/138#issuecomment-1369983652_

**Comment by rcarriga** [comment]
Ah missed this, replied here https://github.com/nvim-neotest/neotest/issues/138#issuecomment-1370630010

**Comment by gegnew** [comment]
:facepalm: 

I should have been able to figure this out, thanks!
