### ISSUE TITLE
[Bug] Wrong case in path to test file on macOS

### ISSUE THREAD

**Issue by fowlie** [nvim-neotest/neotest#190]
On macOS, calling `vim.loop.cwd()` on my machine returns `/Users/mats/Code/...` - notice the capital `C`. On my hard drive, that folder name is `code` with small case. This creates trouble when I use the `neotest-go` adapter, since the `go test` command is case sensitive and thus the test won't run.

A workaround is to rename the `/Users/mats/code` directory to `/Users/mats/Code`, but my OCD doesn't approve. Not sure if this should be reported to the Neovim team instead, but... What do you think?

I'm using macOS Ventura 13.0.1, Neovim 0.8.2 and Neotest v2.6.4.

**Comment by rcarriga** [comment]
Yeah that's pretty bizarre... As it's a core bug I would like to see it discussed in the Neovim repo before taking any action. It could be a luv/libuv bug.

**Comment by fowlie** [comment]
Thanks, I will raise an issue there in stead. I guess this one can be closed then.

Thanks for creating this awesome plugin.

**Comment by fowlie** [comment]
Closing issue in this repo
