### ISSUE TITLE
FixCursorHold is no longer needed with Neovim v0.8.0.

### ISSUE THREAD

**Issue by adworacz** [nvim-neotest/neotest#192]
https://github.com/nvim-neotest/neotest/blob/fee5ce9bdc3dff4706a29b012e75025ab376becb/README.md?plain=1#L34-L35

Per the linked issue, this was fixed upstream.

**Comment by rcarriga** [comment]
Only one of the issues solved by the plugin was addressed so the recommendation still stands https://github.com/antoinemadec/FixCursorHold.nvim/issues/13

**Comment by 616b2f** [comment]
Maybe it makes sense to copy the remaining functionality to neotest? I mean FixCursorHold is clearly not maintained. It is under MIT so with a thank you in README, copying the needed stuff over,  and we could just remove the extra dependency. It is really not that big in terms of line of code. What do you think?

**Comment by rcarriga** [comment]
For what reason though? Removing a dependency isn't a reason in itself. It hasn't had commits in a while but also hasn't had any issues because it is stable, even complete.

**Comment by 616b2f** [comment]
I would say it's better for the UX, because it's less hussle for the user and also reduces the risk that something break in the future, especially if anything this plugin used of it is already feature compete. But this is only my opinion.

**Comment by rcarriga** [comment]
Closing as I don't wish to integrate the functionality into neotest at this time

**Comment by serranomorante** [comment]
Quick question, if I use `vim.opt.swapfile = false` then I don't need [FixCursorHold.nvim](https://github.com/antoinemadec/FixCursorHold.nvim) at all, right?
