### ISSUE TITLE
Running all tests under submobule in test summary panel

### ISSUE THREAD

**Issue by Willem-J-an** [nvim-neotest/neotest#196]
Hi!
I have a Python project where the test files are spread out throughout the submodules. When I am in the neotest summary panel, I would like to be able to run all tests for a specific submodule. When I press 'r' to try to run all tests under a submodule, I generally get 0 tests run, or "failed to import test module".

It this something wrong with my setup, or is this not supported (yet) with neotest?

Thanks!

**Comment by rcarriga** [comment]
Do you have `__init__.py` files in all of your test modules?

**Comment by Willem-J-an** [comment]
Yes I do! This type of functionality also works in vs code with this project.

**Comment by Willem-J-an** [comment]
Re-opened at the correct place.
