### ISSUE TITLE
Indicate that a `position` should not have children

### ISSUE THREAD

**Issue by thenbe** [nvim-neotest/neotest#206]
Hi. I'm [trying to create](https://github.com/thenbe/neotest-playwright/pull/1) multiple `position`'s for a test in `build_position`, but I ran into an issue.

If I don't include a range for the child positions, aka a [`rangeless` position](https://github.com/nvim-neotest/neotest/pull/172), I hit an error for trying to access `range` on a `nil` value, which happens [here](https://github.com/nvim-neotest/neotest/blob/568feb5e9c7c5b7386886ecd4520389153aa7c7d/lua/neotest/lib/positions/init.lua#LL50C9-L50C9).

If I do include a range. The tests will become children of one another. i.e. instead of this:

```
test
├── test A
├── test B
├── test C
```

we get this:

```directory
test
├── test A
│   ├── test B
│   │   ├── test C
```

The way I've [worked around](https://github.com/nvim-neotest/neotest/commit/e27f001cd82d07804664c352af23706940ea4c14) this is by adding an `is_sterile` flag to `Position`. Setting a `position` as `sterile` signals to neotest that it should not have children. But I think a better permanent fix is something like #172 's solution, which uses `Tree:closest_value_for("range")` for range-less positions.

One thing I'm still confused about is why #172 deliberately left out `positions.contains()`. I'm not familiar with this codebase's history so I figured the reason might be outdated? Or do I have a bug in my code?

**Comment by rcarriga** [comment]
Hey awesome to see the work on a new adapter! Can you provide an example of the tests you're trying to create a tree from? It'll make figuring out the issue a lot easier. 
> One thing I'm still confused about is why https://github.com/nvim-neotest/neotest/pull/172 deliberately left out positions.contains()
This was because `positions.contains` is only supposed to be called for positions with ranges or files/directories as that is how the logic works for determining if a position contains another, otherwise there is no way to know.

**Comment by thenbe** [comment]
Basically I'm trying to represent one test node for each project listed in the [`playwright.config.ts`](https://playwright.dev/docs/test-advanced#same-tests-different-configuration) file. Also I wrote I posted a bit about it [here](https://github.com/nvim-neotest/neotest/discussions/203) earlier. If it's not clear, or if there is something specific that would help you let me know.

This is what the desired result looks like using the [workaround](https://github.com/nvim-neotest/neotest/commit/e27f001cd82d07804664c352af23706940ea4c14) I described above:
![image](https://user-images.githubusercontent.com/33713262/218568522-7d8e885c-73e2-4f0a-afe0-a3cb75fe8c39.png)

**Comment by rcarriga** [comment]
Sorry I meant the actual list of positions that you're returning from your `build_position` function. I'd like the structure that you're passing to see where the issue is

**Comment by thenbe** [comment]
Sure. Here is an example:

> What I return from `build_position`:
```lua
local returned_from_build_position = {
  {
    name = "test 1",
    path = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts",
    range = { 2, 4, 4, 2 },
    type = "test",
  },
  {
    id = "a30a6eba6312f6b87ea5-93cb44d41cd8598ed709",
    name = "[chromium] - test 1",
    path = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts",
    range = { 2, 4, 4, 2 },
    type = "test",
  },
  {
    id = "a30a6eba6312f6b87ea5-ec27787a330f7ce50671",
    name = "[firefox] - test 1",
    path = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts",
    range = { 2, 4, 4, 2 },
    type = "test",
  },
  {
    id = "a30a6eba6312f6b87ea5-75e3e7555b70e5a1bf6c",
    name = "[webkit] - test 1",
    path = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts",
    range = { 2, 4, 4, 2 },
    type = "test",
  },
}
```

> From the logfile:
```lua
-- ...te/pack/packer/start/neotest/lua/neotest/client/init.lua:306 | Found
{
  {
    id = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts",
    name = "example.spec.ts",
    path = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts",
    range = { 0, 0, 9, 0 },
    type = "file",
  },
  {
    {
      id = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts::test 1",
      name = "test 1",
      path = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts",
      range = { 2, 4, 4, 2 },
      type = "test",
    },
    {
      {
        id = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts::test 1::[chromium] - test 1",
        name = "[chromium] - test 1",
        path = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts",
        range = { 2, 4, 4, 2 },
        type = "test",
      },
      {
        {
          id = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts::test 1::[chromium] - test 1::[firefox] - test 1",
          name = "[firefox] - test 1",
          path = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts",
          range = { 2, 4, 4, 2 },
          type = "test",
        },
        {
          {
            id = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts::test 1::[chromium] - test 1::[firefox] - test 1::[webkit] - test 1",
            name = "[webkit] - test 1",
            path = "/home/username/projects/playground/pwdemo2/tests/example.spec.ts",
            range = { 2, 4, 4, 2 },
            type = "test",
          },
        },
      },
    },
  },
}
```
> The tree that is rendered

![image](https://user-images.githubusercontent.com/33713262/218823299-e3c7e13d-b176-4efb-931b-1dc5bb104d51.png)

---

Side questions:

1. You may notice that the id's I returned were overwritten. How can I prevent this? Should I be using `position_id`? For reference, the [id](https://playwright.dev/docs/api/class-testcase#test-case-id)'s I'm using were generated by the playwright cli `npx playwright test --list --reporter json`. Those id's should when implementing stuff like [this](https://github.com/thenbe/neotest-playwright/issues/2).

1. Would you recommend not passing a `range` at all for the `parameterized` tests for my use case? It does seem

1. If I don't pass a `range`, should I then keep `nested_tests` set to `true` in `parse_positions`?

**Comment by rcarriga** [comment]
Thanks for that! So the parsed tree is what is "expected" based on what you've provided. You're correct that this is a case for positions with no range attribute instead. I've added support for range-less children to the treesitter parsing so just remove the `range` attribute from the the browser specific tests and the structure should be as you want.

For setting the IDs, yes you should be using the `position_id` option, but you can set the attribute in `build_position` and just use this
```lua
{ 
  position_id = function (position) return position.id end,
  ...
}

**Comment by thenbe** [comment]
This works great. Thank you!
