### ISSUE TITLE
[Feature Request] Running a test/tests from summary panel

### ISSUE THREAD

**Issue by RobertYost** [nvim-neotest/neotest#209]
It would really nice if you could run a test/grouping of tests (e.g. all tests in a describe block in rspec or elixir tests) from the summary panel. Not sure if this is already possible - couldn't seem to find anything that'd do such a thing currently.

**Comment by jfpedroza** [comment]
If you press r while on a test/describe, it will run the test(s).

**Comment by RobertYost** [comment]
@jfpedroza ah gotcha, thank you so much! i'll go ahead and close the issue then

**Comment by rcarriga** [comment]
In case you didn't see it already, the docs contain info on the summary mappings `:h neotest.Config.summary.mappings` and also the summary API `:h neotest.summary` :smile:
