### ISSUE TITLE
Custom argument to `build_position` rpc

### ISSUE THREAD

**Issue by thenbe** [nvim-neotest/neotest#210]
I'm looking for a way to pass the result of a relatively expensive operation to the `build_position` function.

Flow:
- Before `build_position` is called, I call `expensive_operation()` and store the result in a variable called `expensive_table`. `expensive_table` contains test data resolved by the test runner.
- I need access to `expensive_table` in `build_position`. However, since `build_position` runs in a subprocess, I haven't found a way to _directly_ pass `expensive_table` as an argument. I'm not very familiar with lua/neovim's api's, but I've been experimenting with two approaches to get around this:

  1. Write `expensive_table` to a json file. Read the file in each `build_position` call.
  2. Use a workaround such [this](https://github.com/thenbe/neotest/commit/eed4c8a3822cc347f4688b125009d84961231628). Essentially, this enables me to pass `expensive_table` to `parse_position` as part of `opts` table, then be able to access it in `build_position` in the `opts.expensive_table` argument.

Is there a better/more efficient way to do this? In large projects, `build_position` is called many times, so I'm trying to be mindful of performance.

**Comment by rcarriga** [comment]
I'm assuming the expensive table is used across multiple `build_positions` calls. The subprocess library module is considered a public API so you're free to use it for your own needs. You can manually call the subprocess to setup the table with something like this

```lua
local lib = require("neotest.lib")

local M = {}

local expensive_table = nil

function M._build_expensive_table()
  if expensive_table then
    return
  end
  expensive_table = { "some data" }
end

function M.parse_positions(path)
  -- You must check the subprocess is enabled before using it
  if lib.subprocess.enabled() then
    -- This is async and will wait for the function to return
    lib.subprocess.call("require('neotest-playwright')._build_expensive_table()")
  else
    M._build_expensive_table()
  end
  query = [[ ... ]]
  opts = { ... }

  return lib.treesitter.parse_positions(path, query, opts)
end
```

Does that work?

**Comment by thenbe** [comment]
So your snippet shows how to call `expensive_operation()` in a sub-process to avoid blocking the main thread. Then, once the result is ready, it's stored as `expensive_table` in the _main_ process.

What I'm having trouble wrapping my head around is: how can we access that `expensive_table` from the _sub-processes_ that are spawned by neotest?

My understanding is that neotest uses one or more sub-processes to parse the test files, right? In each of those sub-processes, I'd like to access `expensive_table`. But since `expensive_table` is only defined in the _main_ process, how should we expose `expensive_table` to those sub-processes?

**Comment by rcarriga** [comment]
> So your snippet shows how to call expensive_operation() in a sub-process to avoid blocking the main thread. Then, once the result is ready, it's stored as expensive_table in the main process.

You're mixing thread and process so just to be clear: There is a single sub-process spawned (i.e. `neovim --embed`) which is then communicated with over stdio. Whenever any calls are made to the sub-process, they run within this neovim instance, meaning that all state set is available for later use. The instance is long lived so all state set will be available at any stage later.

The snippet above sets module state in the sub-process if it is enabled (`lib.subprocess.enabled()`) so `expensive_table` will be `nil` in the parent process (the interactive neovim instance) but set in the sub-process.

When you call ` lib.treesitter.parse_positions(path, query, opts)`, assuming that you've correctly passed arguments that can be encoded, the `build_positions` function will be called in the subprocess and thus have access to the `expensive_table` value :smile: 

Ref: https://github.com/nvim-neotest/neotest/blob/84955826bfdae41383f05b08ee9e8a7c46211001/lua/neotest/lib/treesitter/init.lua#L165-L169)

**Comment by thenbe** [comment]
Thank you for that explanation! I had incorrectly assumed that `neotest` was making use of multiple ephemeral sub-processes rather than a single long-lived one. Things are making _a lot_ more sense now.
