### ISSUE TITLE
Unable to change color scheme for right side bar items in nvim-neotest due to hard coded highlight group.

### ISSUE THREAD

**Issue by wwnbb** [nvim-neotest/neotest#213]
I am currently facing an issue where I am unable to change the color for the right side bar NeotestDir and NeotestFile highlight groups. Despite trying various methods, including manually setting via hi command and redefining groups, I have not been able to successfully change the colors.

```
  hi default link NeotestFile Normal
  hi default link NeotestDir Normal
```
After executing commands above, `:hi` command still gives me this result:
```
NeotestFile    xxx ctermfg=14 guifg=#00f1f5
NeotestDir     xxx ctermfg=14 guifg=#00f1f5
```

Is there any way to override the hard coded highlight group and change the color scheme for the right side bar? Perhaps there is a possibility to specify the option of setting colors in the configuration? Any guidance or suggestions would be greatly appreciated. Thank you.
<img width="211" alt="Screenshot 2023-02-28 at 00 23 57" src="https://user-images.githubusercontent.com/5105340/221712169-9c1d1ddd-65e4-484c-8c89-3ad8d91c4866.png">

**Comment by rcarriga** [comment]
Remove the `default keyword. See `:h hi-default`

**Comment by wwnbb** [comment]
Thank you!
ended out with following for solarized

```
hi NeotestPassed guifg=#859900
hi NeotestFailed guifg=#F70067
hi NeotestRunning guifg=#268bd2
hi NeotestSkipped guifg=#2aa198
hi NeotestFile guifg=#859900
hi NeotestDir guifg=#268bd2
hi NeotestNamespace guifg=#d33682
hi NeotestFocused gui=bold,underline cterm=bold,underline
hi NeotestIndent guifg=#8B8B8B
hi NeotestExpandMarker guifg=#8094b4
hi NeotestAdapterName guifg=#F70067
hi NeotestWinSelect guifg=#00f1f5 gui=bold
hi NeotestMarked guifg=#F79000 gui=bold
hi NeotestTarget guifg=#F70067
hi NeotestTest guifg=#657b83
```
