### ISSUE TITLE
How to run the test of neotest itself

### ISSUE THREAD

**Issue by scottming** [nvim-neotest/neotest#215]
Hi, I want to write some adapter code and figure out how neotest works, so I need to run the tests of neotest first, but I encountered some problems. 

I can't  run the test with neotest

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/12830256/221768023-45cefc18-f783-4e69-bd6a-86926fc0ca8f.png">

neither with vimtest

<img width="1072" alt="image" src="https://user-images.githubusercontent.com/12830256/221768093-fd1ba7b5-6b95-4b83-9da5-1ad7559db004.png">

but I can run  other plugs' tests, like 

<img width="732" alt="image" src="https://user-images.githubusercontent.com/12830256/221768644-8de9a700-a226-4192-955d-cee62a7db70a.png">

**Comment by rcarriga** [comment]
This is most likely a lazy loading problem. Can you provide a minimal init to reproduce? The bug report template contains a starter one

**Comment by scottming** [comment]
thanks, I can use both lazy or packer to reproduce this:

```lua
local test_dir = "/tmp/nvim-config-2"
vim.opt.runtimepath:append(vim.fn.expand(test_dir))
vim.opt.packpath:append(vim.fn.expand(test_dir))

-- install packer
local install_path = test_dir .. "/pack/packer/start/packer.nvim"
local install_plugins = false

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
	vim.cmd("!git clone https://github.com/wbthomason/packer.nvim " .. install_path)
	vim.cmd("packadd packer.nvim")
	install_plugins = true
end

local packer = require("packer")

packer.init({
	package_root = test_dir .. "/pack",
	compile_path = test_dir .. "/plugin/packer_compiled.lua",
})

packer.startup(function(use)
	use({
		"nvim-neotest/neotest",
		requires = {
			"nvim-lua/plenary.nvim",
			"nvim-treesitter/nvim-treesitter",
			"antoinemadec/FixCursorHold.nvim",
			"nvim-neotest/neotest-plenary",
		},
		config = function()
			require("neotest").setup({
				adapters = {
					require("neotest-plenary"),
				},
			})
		end,
	})
	use({ "nvim-tree/nvim-web-devicons" })
	use({
		"nvim-tree/nvim-tree.lua",
		config = function()
			require("nvim-tree").setup()
		end,
	})

	if install_plugins then
		packer.sync()
	end
end)

-- keymap
local keymap = vim.api.nvim_set_keymap

local opts = { noremap = true, silent = true }
keymap("", "<Space>", "<Nop>", opts)

vim.g.mapleader = " "
vim.g.maplocalleader = " "

keymap("n", "<leader>tt", "<cmd>lua require('neotest').run.run()<cr>", opts)
keymap("n", "<leader>e", "<cmd>NvimTreeToggle<cr>", opts)
keymap("n", "<leader>to", '<cmd>lua require("neotest").output.open({ enter = true })<cr>', opts)
```

In the `neotest` folder use this command `nvim --clean -u ~/.config/nvim-mini-pack/init.lua` and use `<leader>e` to select a test file, then run it.

**Comment by scottming** [comment]
By adding two paths to the rtp, I fixed the problem, but it's also too strange. Why does my rtp contain so little content?

<img width="1424" alt="image" src="https://user-images.githubusercontent.com/12830256/222032415-e71c1b1a-c5f7-4a31-9860-fa36926f72ef.png">

**Comment by rcarriga** [comment]
I'm not actually using lazy.nvim so I'm not sure if it stores plugins the same way as packer. Packer leaves plugins on the RTP but maybe lazy adds to the RTP at runtime. neotest-plenary sets the init.lua/vim used so your own init.lua is not run
https://github.com/rcarriga/neotest-plenary/blob/d49bfd9470f791e7c29149e75d56b6f925bb391b/lua/neotest-plenary/init.lua#L99-L112

**Comment by scottming** [comment]
Yea, but the `init.lua` is using packer, and my friend can not reproduce this issue either.

I solved this problem by adding the `neotest` and some other plugins' paths to RTP manually now.
