### ISSUE TITLE
Dap debug failed with: Adapter doesn't support chosen strategy

### ISSUE THREAD

**Issue by tubzby** [nvim-neotest/neotest#222]
I use neotest-go and neotest-rust,  when I hove to the test function and run:  
**require("neotest").run.run({strategy = "dap"})** 

it prints:
```console
Adapter doesn't support chosen strategy
```

I have setup dap already and it works with my main entry.

**Comment by TimothyPescatore** [comment]
I have now the same issue with C#. Previously everything worked fine. Is the a problem of neotest or from neotest-dotnet or is it my config?

**Comment by rcarriga** [comment]
This is because neotest-dotnet changed its dap implementation, this should be fixed soon with recent changes to neotest. 

See https://github.com/nvim-neotest/neotest/discussions/24#discussioncomment-5641606
