### ISSUE TITLE
[Feature Request] Press `?` for displaying key mappings in summary

### ISSUE THREAD

**Issue by catanzaromj** [nvim-neotest/neotest#230]
The docs do a great job of highlighting functionality and stating key functionality within the test summary window. Is it possible to get a similar summary to show after pressing a specific key? I was thinking of something analogous to what neo-tree implements after pressing `?` in the neo-tree panel. I find myself having to re-open the docs every couple of weeks as I get back into the testing phase of my work.

**Comment by rcarriga** [comment]
On the TODOs, happy to take PRs :smile:

**Comment by llllvvuu** [comment]
Here's a pretty janky workaround: `:h neotest.setup_project()<CR>34k`

you could map a keybinding to that (could even make it specific to the "neotest-summary" filetype)

**Comment by Grafcube** [comment]
I've made PR #379 to fix this issue. It probably needs a little more polish but for now it does the job.
