### ISSUE TITLE
Tried to use neotest, but having a hard time to keymappings

### ISSUE THREAD

**Issue by sittim** [nvim-neotest/neotest#241]
I am having a hard time with figuring out the keybindings?  I have been using the vim-test and my configuration has been like so:

`
nmap <silent> <leader>t :TestNearest<CR>
nmap <silent> <leader>T :TestFile<CR>
nmap <silent> <leader>a :TestSuite<CR>
nmap <silent> <leader>l :TestLast<CR>
nmap <silent> <leader>g :TestVisit<CR>
`

How can I set the NeoTest to trigger to run tests?

**Comment by fnune** [comment]
Here's an example:

```lua
vim.keymap.set("n", "<leader>t", function() require("neotest").run.run() end)
vim.keymap.set("n", "<leader>T", function() require("neotest").run.run(vim.fn.expand('%')) end)
```

Or Vimscript:

```vim
nmap <leader>t :lua require('neotest').run.run()<cr>
nmap <leader>T :lua require('neotest').run.run(expand('%'))<cr>
```

I've tested the Lua but not the Vimscript.

To find more functions you could run, see:

```
:h neotest.run
```

In there, you'll see `run_last` and others.
