### ISSUE TITLE
have neotest.output stay

### ISSUE THREAD

**Issue by fdelacruz** [nvim-neotest/neotest#250]
<img width="522" alt="Screen Shot 2023-05-16 at 5 20 29 PM" src="https://github.com/nvim-neotest/neotest/assets/148098/47ebd657-a288-4802-b992-3c662451baff">

This output displays the test for about a second before is disappears.
Is it possible to have it stay?
 `:h neotest.output` tells me i can manually call the "consumer" with..
`lua require("neotest").output.open({ enter = true })`
That's really cool, but maybe i can make it stay put.

I have a very minimal setup right now:

```
local M = {}

function M.setup()
  require("neotest").setup {
    adapters = {
      require "neotest-python" {
        dap = {
          justMyCode = false,
          console = "integratedTerminal"
        },
        args = { "--log-level", "DEBUG", "--quiet" },
        runner = "pytest",
      },
      require "neotest-jest",
    },
  }
end

return M
```

and

 ```
 {
    "nvim-neotest/neotest",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-treesitter/nvim-treesitter",
      "antoinemadec/FixCursorHold.nvim",
      "nvim-neotest/neotest-python",
      "haydenmeade/neotest-jest",
    },
    lazy = true,
    config = function()
      require("user.neotest").setup()
    end,
  },
```

**Comment by catanzaromj** [comment]
@fdelacruz I don't know why your output window is flickering, but here's a possible workaround.

After you run a test, put your cursor anywhere in the test and try `require("neotest").output.open()` (I have this mapped to a key mapping). Does it stay up then? If you move the cursor, it should disappear. If you issue the command twice, you should be able to enter into the output window for scrolling.

**Comment by mszenfeld** [comment]
@albertocerrone I have fixed the same problem by disabling the quick fix in the configuration:
```
...
quickfix = {
    enabled = false,
},
...
```

**Comment by albertocerrone** [comment]
Thank you so much @mszenfeld! That fixed my issue ❤️
