### ISSUE TITLE
[BUG] "E482: Can 't open file /path/to/manifest for writing: no such file or directory"

### ISSUE THREAD

**Issue by ChristophSchmidpeter** [nvim-neotest/neotest#251]
**NeoVim Version**
Output of `nvim --version`

**Describe the bug**

**To Reproduce**
1. `nvim --clean -u minimal.lua`
2. Note `E482: Can't open file /path/to/manifest for writing: no such file or directory` error

**Example test files to reproduce**
[minimal.lua.txt](https://github.com/nvim-neotest/neotest/files/11489935/minimal.lua.txt)

**Expected behavior**
No error message

**Logs**
Set log level, but I cannot find logs. Where can I find them?

**Comment by rcarriga** [comment]
This is just a packer error message that has no effect, closing as it's not related to neotest but feel free to submit a minimal init which avoids the issue
