### ISSUE TITLE
[BUG] Weird characters appears in attach buffers.

### ISSUE THREAD

**Issue by pBorak** [nvim-neotest/neotest#265]
**NeoVim Version**
Output of `nvim --version`
NVIM v0.10.0-dev-3133+g3688735c2-Homebrew

**Describe the bug**

Weird duplicated characters appear after attaching to the test. Everything works okay until I exit attach window and attach again. Then there will be as many duplicated characters as many I repeat this operation. I was able to find the commit that introduced this regression, this one =>  https://github.com/nvim-neotest/neotest/commit/972a7dc9dfe860649edaf89e08c514a98d3a2a09.

https://github.com/nvim-neotest/neotest/assets/45797239/a81914e8-09a0-4612-b243-f5dcd860a116

I don't think it's test/setup specific as it was working for me just fine before this commit. That being said If you need a more detailed setup just let me know.

**Comment by noon-ng** [comment]
Just dropping by to add that if you do that again, your input will be tripled (and quadrupled and so forth)

**Comment by rcarriga** [comment]
This should be fixed in latest master :smile:
