### ISSUE TITLE
Wrong use of :format in nio.task.run() step error reporting

### ISSUE THREAD

**Issue by wiertel** [nvim-neotest/neotest#273]
I've got an error with raw format string - no values where substituted. Seeing other lines with `error` and `:format` my guess is that parenthesis are wrong.

https://github.com/nvim-neotest/neotest/blob/fb0b31ae1dcdc7d68af5c66db4434ae5ebeffcfc/lua/nio/tasks.lua#L129-L133

**Comment by rcarriga** [comment]
Can you provide the error that you're seeing?

**Comment by wiertel** [comment]
```
Error executing luv callback:
...wiertel/.local/share/nvim/lazy/neotest/lua/nio/tasks.lua:129: Async internal error: expected function, got %s
Context: %s
%s
stack traceback:
        [C]: in function 'error'
        ...wiertel/.local/share/nvim/lazy/neotest/lua/nio/tasks.lua:129: in function 'cb'
        ...wiertel/.local/share/nvim/lazy/neotest/lua/nio/tasks.lua:179: in function <...wiertel/.local/share/nvim/lazy/neotest/lua/nio/tasks.lua:178>
```
The error is caused by [neotest-gtest](https://github.com/alfaix/neotest-gtest) plugin which seems to need an update. While patching it to work for me - dirty and quick - I've stumbled on this not so useful message.

**Comment by rcarriga** [comment]
Ah my bad, I misunderstood what the issue was. Should be fixed now :smile:

**Comment by wiertel** [comment]
Thanks. I though you wanted to reproduce the error. Here's a snippet that shows that error message. Might not be necessary now, but took me a while to extract that (probably not minimal), so I will share it anyway.
``` lua
local async = require('plenary.async')
local input = async.wrap(vim.ui.input, 2)

function ask()
  local resp = input({prompt='What?', default='', completion='file'})
  return resp, nil
end

require('neotest.async').run(ask, function()
  print('Done')
end)
```
