### ISSUE TITLE
Run All?

### ISSUE THREAD

**Issue by hahuang65** [nvim-neotest/neotest#28]
Is there a command to run the entire test suite of a project?

**Comment by hahuang65** [comment]
Thanks @stevearc your suggestion works pretty well in most cases!

**Comment by rcarriga** [comment]
Yeah I've always just used `getcwd()` but I can see how that wouldn't work all the time. Not sure of what a nice interface would be. Simple solution I think would have a function to get the root directory and then supply that to the run function.
E.g. `neotest.run.run(neotest.run.root())` though if there's a way to extend the current `run` args to say "run everything" then I'd prefer that, so open to ideas

**Comment by rcarriga** [comment]
OK I've added a `suite` arg to `neotest.run.run`, so just set `{ suite = true }` in the args :smile: 

The `root()` function would have required users to wrap it in plenary's async library which would be a pain

**Comment by olimorris** [comment]
@rcarriga testing this with multiple adapters in the same Neovim instance and it only runs tests for the first adapter.

**Comment by rcarriga** [comment]
That is intended behaviour. I've added `neotest.run.adapters()` to get the known adapter IDs.
```lua
      for _, adapter_id in ipairs(neotest.run.adapters()) do
        neotest.run.run({ suite = true, adapter = adapter_id })
      end
```
