### ISSUE TITLE
[DOCS] or [BUG]: How does test detection work when using typescript and neovim-vim-test // how to debug

### ISSUE THREAD

**Issue by ships** [nvim-neotest/neotest#283]
Hi friends, I use neotest native testing adapters for a few languages (rust, ruby, elixir, python) but delegate to `neotest-vim-test` for all others, in particular Typescript because ostensibly `vim-test` can integrate with the [AVA framework](https://github.com/avajs/ava) which I use instead of jest.

However I think my configuration must be wrong and I would like to debug. It may be workspace related however. Here are my symptoms:

in a typescript or javascript file, when I call my binding to `require("neotest").run.run()` I get `No tests found`.
in a typescript or javascript file, When I call vim-test's native `:TestNearest` I am able to run my tests.

in a Go file, both vim-test and neotest work natively as expected, neotest invoking vim-test
in a Rust file, both vim-test and neotest work natively as expected, but neotest doesn't call vim-test

My `neovim-test` config (lazy.nvim) is like that:

```lua
			require("neotest").setup({
				status = {
					signs = false,
					virtual_text = true,
				},
				adapters = {
					require("neotest-rust"),
					require("neotest-python"),
					require("neotest-elixir"),
					require("neotest-rspec"),
					-- vim-test for all other types. use exclusion to match above lines.
					require("neotest-vim-test")({ ignore_filetypes = { "python", "rust", "ruby", "elixir" } }),
				},
			})
```

I would love any guidance you have as to how I can figure out where the ball is being dropped. It may be a special behavior given the various eccentricities of javascript ecosystem. But I would like to know how to follow my nose towards why no tests are detected in this case.

**Comment by ships** [comment]
As I continue debugging this, I have discovered these log lines:

```
INFO | 2023-08-14T20:15:41Z-0600 | ...l/share/nvim/lazy/neotest/lua/neotest/lib/subprocess.lua:84 | CHILD | Connected to parent instance
INFO | 2023-08-14T20:15:41Z-0600 | ...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:380 | Initialising client
INFO | 2023-08-14T20:15:41Z-0600 | ...are/nvim/lazy/neotest/lua/neotest/client/events/init.lua:48 | Emitting starting event
DEBUG | 2023-08-14T20:15:41Z-0600 | ...are/nvim/lazy/neotest/lua/neotest/client/events/init.lua:50 | Calling listener summary for event starting
INFO | 2023-08-14T20:15:41Z-0600 | ...al/share/nvim/lazy/neotest/lua/neotest/adapters/init.lua:18 | Found 1 adapters for directory /Users/eve/[redacted]
DEBUG | 2023-08-14T20:15:41Z-0600 | ...al/share/nvim/lazy/neotest/lua/neotest/adapters/init.lua:19 | Adapters: { {
    adapter = {
      build_spec = <function 1>,
      discover_positions = <function 2>,
      filter_dir = <function 3>,
      is_test_file = <function 4>,
      name = "neotest-rspec",
      results = <function 5>,
      root = <function 6>,
      <metatable> = {
        __call = <function 7>
      }
    },
    root = "/Users/eve/[redacted]"
  } }
INFO | 2023-08-14T20:15:41Z-0600 | ...ocal/share/nvim/lazy/neotest/lua/neotest/client/init.lua:281 | Searching /Users/eve/[redacted] for test files
```

From this, I can see that for some reason neotest thinks this is a Ruby test suite, when in reality they are all Typescript files. I am unsure at this time on what basis it makes this determination but i bet `neotest-rspec` doesn't pick up any `.test.ts` files, which is why it says `No tests found`.

**Comment by rcarriga** [comment]
It's because `neotest-rspec` treats any directory with a `.gitignore` as a root directory and so `neotest-vim-test` is not used. You'll need to open an issue there to change this behaviour.

Ref: https://github.com/olimorris/neotest-rspec/blob/5fe7d860def0539f7f5d375fbf9c481c097062c8/lua/neotest-rspec/config.lua#L11-L13
