### ISSUE TITLE
[BUG] Position already running

### ISSUE THREAD

**Issue by muhrizkiakbar** [nvim-neotest/neotest#284]
**NeoVim Version**
0.9.1

**Describe the bug**
i am using neotest-rspec, but when i try to call `:lua require("neotest").run.run()` the log showing error with message Position already running

**To Reproduce**
please check my [nvim dotfile]( https://github.com/muhrizkiakbar/dotfiles/tree/main/nvim)

**Current config**
![Screen Shot 2023-08-17 at 17 22 46](https://github.com/nvim-neotest/neotest/assets/18720002/426f5670-2639-40ab-9811-5cbf528f92e0)
![Screen Shot 2023-08-17 at 17 23 18](https://github.com/nvim-neotest/neotest/assets/18720002/11ef619c-7146-4ec1-91e6-8f9013ba119f)

**Logfile**
![Screen Shot 2023-08-17 at 17 23 38](https://github.com/nvim-neotest/neotest/assets/18720002/564d76e1-c00a-436d-904a-f483865e5ae9)

**Comment by rcarriga** [comment]
Please fill out the requested info. I'm not going to debug an entire neovim config and you haven't provided any information on how to run the test. I've never used Ruby before so have no idea how the environment should be setup.

The template also states to set the log level to debug and paste the logs, not paste a screenshot.

The more information you provide, the easier it will be to help debug the issue
