### ISSUE TITLE
[FEAT] visit/open the file containing the test from the test summary panel

### ISSUE THREAD

**Issue by sajjathossain** [nvim-neotest/neotest#287]
from the test summary panel, I can run the tests. but if a test fails I can not just jump to the failing test file. I manually have to search the file containing it. It would be nice to have this feature. it would make things easier.

**Comment by llllvvuu** [comment]
This actually exists, see `:h neotest.Config.summary.mapping`. The default value for jumpto is "i", as per:

https://github.com/nvim-neotest/neotest/blob/bec7be0f13ee19c85561943fc5f7b8daa4f4d465/doc/neotest.txt#L292

Understandably this should be more discoverable in the UI (#230)
