### ISSUE TITLE
[Feat] Support  viewing output for `watch` mode 

### ISSUE THREAD

**Issue by tuanbass** [nvim-neotest/neotest#292]
Most test framework has `watch` mode, that watch src file, auto compile and run test.
But it's likely `neotest` [wait](https://github.com/nvim-neotest/neotest/blob/master/lua/neotest/client/runner.lua#L129-L133) until `test` process finish before fullfill the test result. 
The consequence is, even when all test cases are finished in `watch`  mode,   the test output is not fullfilled into neotest.
Hence, here is the result of `neotest output`
![image](https://github.com/nvim-neotest/neotest/assets/9334023/1b60f891-6f64-4b9a-9cc4-73c28363183f)

Can we provide the mechanism to update the test output in these cases?

**Comment by rcarriga** [comment]
You can attach to the running process to see the output, using either the `attach` mapping in the summary or `neotest.run.attach()`

**Comment by tuanbass** [comment]
> You can attach to the running process to see the output, using either the `attach` mapping in the summary or `neotest.run.attach()`

Thanks, it resolves my issue perfectly.
