### ISSUE TITLE
[BUG] Test is unable not rerun if succeed

### ISSUE THREAD

**Issue by ivanlee1999** [nvim-neotest/neotest#301]
If a test succeed and I try to run it a second time, the test will simply return the former test results rather than rerun the test again..

I have a random number generator in the test, but if I rerun the test and test succeed, the logs showed the random number are not changing by which I know that the test is not really rerun again.

**Comment by rcarriga** [comment]
I have no way to reproduce this so I am closing. Provide the information required in the bug report template if you want me to investigate further
