### ISSUE TITLE
Debugging setup

### ISSUE THREAD

**Issue by hahuang65** [nvim-neotest/neotest#31]
When running
```
require("neotest").run.run({strategy = "dap"})
```
I keep getting
```
The selected configuration references adapter `nil`, but dap.adapters.nil is undefined
```

This is using `neotest-go`. I'm guessing this is because that adapter does not support DAP yet? How would I be able to tell if this were the case?

Or, in the situation where it does support DAP, I must have mis-configured something?

Here is my configuration:

```
require("neotest").setup({
  adapters = {
    require("neotest-python")({
      dap = { justMyCode = false },
    }),
    require("neotest-go"),
    require("neotest-rspec")
  }
})
```

**Comment by ofrades** [comment]
It also happens to me with node :eyes:

**Comment by akinsho** [comment]
@hahuang65 the dap strategy hasn't been build into `neotest-go` someone needs to make a PR for that since at the moment the argument isn't used and there is no dap config for go. I don't know what that should even look like, so someone who does should contribute that change in that repo

**Comment by rcarriga** [comment]
I've added a change to notify users when the adapter doesn't support debugging.

@akinsho FYI this might be useful https://github.com/rcarriga/vim-ultest/wiki/Debugging-Recipes#gotest. At the time of writing that vscode-go didn't emit an error exit code which is why the result parsing is there. I never got delve working but didn't put much time into it

**Comment by akinsho** [comment]
Thanks, @rcarriga 👍🏿 I'm pretty sure also that `nvim-dap` has a recipe for it in there, and it definitely works with https://github.com/ray-x/go.nvim which has a config that works, so someone could grab that I haven't looked into it further though, someone else feel free to pick this up as I'm not working on it, as I haven't got the time (or present need).

**Comment by rcarriga** [comment]
Going to close this as the functionality of notifying users when nvim-dap is not supported is there. Adapter specific issues can be raised in their repos
