### ISSUE TITLE
[Feature] Code Coverage Indicators

### ISSUE THREAD

**Issue by sand4rt** [nvim-neotest/neotest#312]
First of all, thank you for this awesome plugin!

It would probably be a lot of work, but it would be great to have code coverage indicators ala Wallaby.js:

![image](https://github.com/nvim-neotest/neotest/assets/17591696/35f4bec6-e3cf-44da-a6bb-1deb0911a760)

> When executing your tests and code, Wallaby calculates code coverage to identify which statements of your code have been executed and which statements have not.
>
> Code coverage for your application code is displayed in the left margin of your editor and is updated in real-time. As soon as you start changing your code, the coverage will be automatically updated.

_*[https://wallabyjs.com/docs/intro/coverage.html#editor-code-coverage-indicators](https://wallabyjs.com/docs/intro/coverage.html#editor-code-coverage-indicators)_

What the coverage indicators mean:

- **Gray:** if you see a gray square next to a line of code, it means that the line of code is not covered by any of your tests.
- **Yellow:** if you see a yellow square next to a line of code, it means that the line of code is only partially covered by your tests.
- **Green:** if you see a green square next to a line of code, it means that the line of code is covered by at least one of your tests.
- **Pink:** if you see a pink square next to a line of code, it means that the line of code is on the execution path of a failing test.
- **Red:** if you see a red square next to a line of code, it means that the line of code is the source of an error or failed expectation, or in the stack of an error.

**Comment by jan-xyz** [comment]
I am achieving this by using https://github.com/andythigpen/nvim-coverage. You can setup custom arguments for your test runner to export coverage data and then just display it. E.g. for Go I am doing this:

```lua
local nt = require("neotest")
local cov = require("coverage")

cov.setup()
nt.setup({
  adapters = {
    require("neotest-go")({
      args = { "-coverprofile=coverage.out" },
    }),
  },
})
```

and then I run 

```lua
nt.run.run(vim.fn.getcwd())
cov.load(true)
```
