### ISSUE TITLE
add status constants 

### ISSUE THREAD

**Issue by TheSnakeWitcher** [nvim-neotest/neotest#334]
Hi, I am developing an adapter to integrate neotest with [hardhat](https://hardhat.org/). I have a code like these

```lua
M.STATUS = {
    passed = "passed",
    skiped = "skipped",
    failed = "failed",
}
```
And I found that neotest-go adapter [here](https://github.com/nvim-neotest/neotest-go/blob/main/lua/neotest-go/test_status.lua) has a code like these

```lua
local test_statuses = {
   -- ...
  pass = "passed", -- the test passed
  fail = "failed", -- the test or benchmark failed
  skip = "skipped", -- the test was skipped or the package contained no tests
}
``` 

I think that probably other adapters use similar declarations to set the `status` field of a `neotest.Result` Maybe these constants could be defined in neotest, that way all plugins could use it and we avoid code duplication, maybe a module like `neotest.lib.constants` would be cool.

I personally use these other constants too when computing `command` field of the `neotest.RunSpec`.

```lua
NODE_TYPES = {
    dir = "dir",
    file = "file",
    namespace = "namespace",
    test = "test",
}
```

**Comment by rcarriga** [comment]
I've added enums for both to `neotest.types` :smile:

**Comment by TheSnakeWitcher** [comment]
Nice work, chears :smile:
