### ISSUE TITLE
vim-ultest test position jumps

### ISSUE THREAD

**Issue by axieax** [nvim-neotest/neotest#35]
Hi, just wondering whether it is possible to do something like this from vim-ultest?

```vim
nmap ]t <Plug>(ultest-next-fail)
nmap [t <Plug>(ultest-prev-fail)
```

Also, not sure what the highlight group is for the background of the floating window. Is it possible to make this partially transparent (winblend)?

**Comment by rcarriga** [comment]
I've added the jump consumer so have a look at `:h neotest.jump` :smile:

Also I've added an `options` key to the floating windows opts so you can provide the following to setup table
```lua
  floating = {
    options = {
      winblend = 50
    },
  },
```

**Comment by axieax** [comment]
Thanks so much for the quick additions! Also, just wondering if there is a better way of defining adapters (especially for the ignore_file_types of vim-test). I understand that it may not be so easy to expose the filetypes from each adapter due to `is_test_file`.

```lua
local adapter_config = {
  go = {
    filetypes = { "go" },
  },
  jest = {
    filetypes = { "javascript", "typescript", "javascriptreact", "typescriptreact", "coffee" },
  },
  python = {
    filetypes = { "python" },
  },
  plenary = {
    filetypes = { "lua" },
  },
}

local adapters = {}
for _, adapter in ipairs(vim.tbl_keys(adapter_config)) do
  local ok, neotest_adapter = pcall(require, "neotest-" .. adapter)
  if ok then
    table.insert(adapters, neotest_adapter)
  end
end

local filetypes = {}
for _, adapter in ipairs(adapter_config) do
  vim.list_extend(filetypes, adapter.filetypes)
end
table.insert(
  adapters,
  require("neotest-vim-test")({
    -- disable adapter filetypes above
    ignore_file_types = filetypes,
  })
)

require("neotest").setup({
  adapters = adapters,
  -- floating = { options = { winblend = 80 } },
})
```

**Comment by rcarriga** [comment]
Hmm I think the best way would be instead to add `enabled_filetypes` for neotest-vim-test so everything is disabled by default

**Comment by rcarriga** [comment]
OK I've added an `allow_file_types` option to neotest-vim-test

**Comment by axieax** [comment]
o.0 how would I adapt the config above to use that option?

**Comment by axieax** [comment]
Hmm my use case is to find a way to automatically ignore filetypes for adapters that have been registered in the setup function (such as neotest-go automatically prioritising itself over vim-test, neotest-python automatically prioritising itself over vim-test etc.)

**Comment by rcarriga** [comment]
I'm not sure why you need the safety check of if adapters are installed but that is a very unique case that won't be covered by neotest. You'll have to do it manually as have above if you want to go that route

**Comment by axieax** [comment]
Oh my intention was just to prevent conflicts between the newer adapters and the default ones provided by vim-test. Sorry for any potential misunderstandings.
