### ISSUE TITLE
feature request: Lazy load

### ISSUE THREAD

**Issue by pedro757** [nvim-neotest/neotest#36]
I used to lazy load **vim-ultest** using **keys** and by **cmd** packer properties this way:

```lua
    use {
      "rcarriga/vim-ultest",
      opt = true,
      run = ":UpdateRemotePlugins",

---- LIKE THIS
      cmd = { "Ultest", "UltestNearest", "UltestSummary" },
      keys = {
        "<Plug>(ultest-run-nearest)",
        "<Plug>(ultest-run-file)",
        "<Plug>(ultest-summary-toggle)",
      },


      requires = {
        {
          "vim-test/vim-test",
          cmd = { "TestNearest", "TestFile" },
          opt = true,
        }
      },
    }
```

But I checked out the documentation and there's no `<Plug>(mappingToRunTest)` or `:CommandToRunTest` maybe we should add a few commands and a few mappings

### Is there other way to lazy load this plugin?

**Comment by pedro757** [comment]
I can do it but I just want confirmation if this is the right way to go or maybe I am missing something.

**Comment by pedro757** [comment]
Its dependencies still load on VimEnter, for example `vim-test`, but maybe this issue is out of scope.

**Comment by rcarriga** [comment]
Packer supports lazy loading lua modules, so you can use that.
```lua
  module = string or list      -- Specifies Lua module names for require. When requiring a string which starts
                               -- with one of these module names, the plugin will be loaded.
```

**Comment by pedro757** [comment]
I think that feature is not related to this problem. it's for naming modules so you can call them in other places.

I ran `vim --startuptime h.log` and I got this:
![image](https://user-images.githubusercontent.com/30637426/179135087-dc6aad0e-f8c2-4bbb-8c47-81b0e2e4fae9.png)

This is what I mean, I noticed a change in the startuptime when switching from the vim-ultest to neotest, Is there a way to just load this plugin when I press certain keys like I used to do in vim-ultest

```lua
      keys = {
        "<Plug>(ultest-run-nearest)",
        "<Plug>(ultest-run-file)",
        "<Plug>(ultest-summary-toggle)",
      },
```

I know this is just a triviality but I don't like spending 6 ms in neotest-python, 4 ms in neotest.lib 3 ms in neotest-jest.
I don't even use this plugin on a daily basis, I just want to load it when I need it.

**Comment by rcarriga** [comment]
`module` definitely does lazy load neotest, if you're seeing it load on startup it's because you're calling it in your config. If you don't want to use that, you can define your own mappings that are used for lazy loading
