### ISSUE TITLE
[QUESTION] Is FixCursorHold.nvim still required?

### ISSUE THREAD

**Issue by eruizc-dev** [nvim-neotest/neotest#361]
The [installation instructions](https://github.com/nvim-neotest/neotest?tab=readme-ov-file#installation) still declare [FixCursorHold.nvim](https://github.com/antoinemadec/FixCursorHold.nvim) as a dependency, which has been [deprecated two years ago](https://github.com/antoinemadec/FixCursorHold.nvim/commit/70a9516a64668cbfe59f31b66d0a21678c5e9b12) as it is no longer needed.

Is it still required for some obscure reason or does the README need to be updated? I've removed the dependency from my local installation and have not noticed any difference

**Comment by rcarriga** [comment]
See https://github.com/antoinemadec/FixCursorHold.nvim/issues/13
