### ISSUE TITLE
[BUG] NerdFonts `v3` broke the `mdi-test-tube` icon for neotest in nvim-notify

### ISSUE THREAD

**Issue by h0adp0re** [nvim-neotest/neotest#370]
**Describe the bug**
When a Neotest notification appears via nvim-notify, the icon is an Arabic symbol instead of the old test-tube.
![Screenshot 2024-02-21 at 01 20 14](https://github.com/nvim-neotest/neotest/assets/11251772/cdb218b3-bfdd-4d39-8244-e41fdf1441ed)
This line needs to be updated:
https://github.com/nvim-neotest/neotest/blob/f6048f32be831907fb15018af2688ff6633704fc/lua/neotest/lib/init.lua#L42

**To Reproduce**
Use Neotest with nerd-fonts `v3`.

**More Info**
https://github.com/ryanoasis/nerd-fonts/issues/1190

**Possible Fix**
https://github.com/loichyan/nerdfix

**Comment by h0adp0re** [comment]
And offtopic — for some reason I got an email immediately after filing this issue. Is this a GH bug?
> Add issues to tracking project: All jobs have failed
> workflow run failed in 4 seconds - master (https://github.com/nvim-neotest/neotest/commit/f6048f32be831907fb15018af2688ff6633704fc)

**Comment by Finii** [comment]
`FB67` had to be removed because the Nerd Font icons in that plane broke a lot international fonts. That codepoint is not 'free to use' (i.e. not PUA).
For that reason all MD icons got moved with Nerd Fonts v3.

![image](https://github.com/nvim-neotest/neotest/assets/16012374/78d68c55-7696-4d95-be8c-2acec2469c92)

**Comment by rcarriga** [comment]
Switched to using an icon from codicons to be consistent and made it configurable

**Comment by rcarriga** [comment]
> And offtopic — for some reason I got an email immediately after filing this issue. Is this a GH bug?

I've no idea why you got that, it must be :sweat_smile:
