### ISSUE TITLE
[BUG] lua/neotest-dotnet/strategies/netcoredbg.lua:62: attempt to index field 'dap' (a nil value)

### ISSUE THREAD

**Issue by VladimirBeliakov** [nvim-neotest/neotest#375]
**NeoVim Version**
NVIM v0.10.0-dev-2507+g3df1211ebc
Build type: RelWithDebInfo
LuaJIT 2.1.1702233742
Run "nvim -V1 -v" for more info

**Describe the bug**
Run tests by issuing the following command
```
require("neotest").run.run({ strategy = "dap" })
```

Sorry for not providing any additional information but the bug is too obvious :)

For some reason this line

https://github.com/Issafalcon/neotest-dotnet/blob/c19df2a139d88c5b4130b830d2cbe63a2c6c6c0c/lua/neotest-dotnet/init.lua#L150C27-L150C35

was not changed in the commit where the line

https://github.com/Issafalcon/neotest-dotnet/blob/c19df2a139d88c5b4130b830d2cbe63a2c6c6c0c/lua/neotest-dotnet/init.lua#L7

was changed.

So it causes an error on this line

https://github.com/Issafalcon/neotest-dotnet/blob/c19df2a139d88c5b4130b830d2cbe63a2c6c6c0c/lua/neotest-dotnet/strategies/netcoredbg.lua#L62

**Comment by pfesenmeier** [comment]
Did you mean to open this issue in https://github.com/Issafalcon/neotest-dotnet?

**Comment by VladimirBeliakov** [comment]
Huge facepalm. Sorry, my bad. Closing the issue.
