### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by dahmc** [nvim-neotest/neotest#38]
I've been really enjoying ultest, so I am very excited about neotest. Thanks for building such great software.

Here are a few things I've noticed on latest neotest:

1. `lua require("neotest").output.open({ enter = true })` after running a test does not seem to work
<img width="460" alt="CleanShot 2022-06-23 at 08 27 27@2x" src="https://user-images.githubusercontent.com/75008413/175230566-32e7f6cc-a41c-4da8-ab4f-815378cfa969.png">

2. Running a test and then doing `lua require("neotest").run.attach()` will open the test output, but it will immediately close after the test finishes. How do I keep this window open?

3. The status signs in the gutter area aren't rendering properly and I don't know how to change them.
<img width="395" alt="CleanShot 2022-06-23 at 08 26 51@2x" src="https://user-images.githubusercontent.com/75008413/175230813-a019113b-7ce4-4cb8-826e-2684056eb623.png">

The Readme says to do a `:h neotest.status` but all is says is

```
A consumer that displays the results of tests as signs beside their
declaration. This consumer is completely passive and so has no interface.
```
That doesn't tell me how to change the symbols.

**Comment by rcarriga** [comment]
1. This seems like an adapter issue, can you try with a different adapter?
2. I've just pushed a change to keep the window open :smile: 
3. See `:h neotest.setup()` for the config defaults, the icons are used throughout so they're defined globally.

**Comment by dahmc** [comment]
Thanks for the quick response

1. I've used `neatest-jest`, after switching to `neotest-vim-test` it works
2. Awesome, works great!
3. Got it, thanks. All good now.
