### ISSUE TITLE
Summary mappings

### ISSUE THREAD

**Issue by dahmc** [nvim-neotest/neotest#39]
Could you please provide a quick example of how to use the summary window mappings?

The help file lists a table of mappings but I don't know how to trigger/map them properly.

I've tried `lua require("neotest").summary.run()` but it doesn't work.

**Comment by dahmc** [comment]
Nevermind, I found the mappings in `:h neotest.setup()` :)

**Comment by prdanelli** [comment]
@dahmc This really helped me, as I was really struggling find the keybindings I needed. An expanded readme would be super useful to those of us who are less familiar with Vim :)

**Comment by rcarriga** [comment]
I've mentioned `neotest.setup()` as well in the README so users will easily see defaults. I've also pointed to https://github.com/folke/lua-dev.nvim which will allow users to easily get autocomplete for setup values.

**Comment by prdanelli** [comment]
@rcarriga thank you for your help and your contributions.
