### ISSUE TITLE
Can't run tests on describe blocks, only single tests

### ISSUE THREAD

**Issue by dahmc** [nvim-neotest/neotest#40]
In a JS test file, let's say I have a bunch of grouped tests

```
  describe('Test group', () => {
    test('test 1', () => {
      expect(1).toBeTruthy();
    });

    test('test 2', () => {
      expect(0).toBeTruthy();
    });
  });
```

So I can hover the `test 1` and run it, no problem. Same for `test 2`

However, it I want to run the whole describe block `Test group`, it does not work.

It will put the running indicator on the group and all subtests, but it never runs.

Attach says `no running process found` and output open says `no output for test group`

Same behaviour running from the summary window

Edit: using `neotest-vim-test`. This behaviour worked in ultest

**Comment by rcarriga** [comment]
Should be working as expected now :smile:

**Comment by dahmc** [comment]
Thanks for the quick fix, appreciate it :)

Works great now!
