### ISSUE TITLE
Font Glyphs

### ISSUE THREAD

**Issue by hahuang65** [nvim-neotest/neotest#41]
My terminal comes bundled with https://github.com/ryanoasis/powerline-extra-symbols and https://www.google.com/get/noto/help/emoji/ but it seems neither of those have all the font glyphs that this project uses...

Any recommendations on a font set that does include all the required glyphs?

**Comment by rcarriga** [comment]
You'll want something that supports [Nerd Fonts](https://www.nerdfonts.com/). I personally use JetBrains Mono patched font but there are many more patched fonts. You can find them here https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts

You can also change the icons to something your font does support if you don't want to change

**Comment by hahuang65** [comment]
Hmm... I am using a patched Jetbrains Mono. I wonder why it's missing some glyphs...

**Comment by hahuang65** [comment]
I've updated my JetBrains Mono Nerd Font to the latest and still nothing. I'm using wezterm which can configure a fallback font.

Is it at all possible your terminal emulator is also falling back to a different font for that glyph?

**Comment by hahuang65** [comment]
I had to grab Noto Sans Symbols 2 for this glyph to show up.

**Comment by rcarriga** [comment]
Ah apologies, you're right I'm also using codicons https://github.com/microsoft/vscode-codicons :facepalm:

**Comment by Sangdol** [comment]
For me, Noto Sans Symbols didn't work for some reason, and `font-codicons` didn't show symbols for [exa](https://the.exa.website/features/icons).

`font-symbols-only-nerd-font` worked well for this project and exa.

You can install it with brew if you use macOS:

```sh
brew tap homebrew/cask-fonts
brew install font-symbols-only-nerd-font --cask
```

**Comment by rcarriga** [comment]
I've added links to the README for how to patch any font with codicons if your terminal doesn't support fallback
