### ISSUE TITLE
[Feature Request] Enable setting custom environment variables for summary runs

### ISSUE THREAD

**Issue by lukerops** [nvim-neotest/neotest#431]
I use a custom set of environment variables for each project I work on and it works successfully with the lua API, but sometimes I want to run all the tests in the project and I can't get it to work. Running the test in summary doesn't allow me to set the environment variables I want to use.

**Comment by rcarriga** [comment]
I've added a new `augment` option for the run consumer if you want to check it out in https://github.com/nvim-neotest/neotest/pull/437, I believe it'll work for your use case

**Comment by lukerops** [comment]
I tried with your PR code and it worked perfectly!!
