### ISSUE TITLE
Text output render issue

### ISSUE THREAD

**Issue by sidlatau** [nvim-neotest/neotest#44]
I see some strange behavior in the test output popup. When I open it from the test file it cuts text that does not fit to popup:
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/4973296/176277224-45732fd2-a045-4015-8f30-762992543196.png">
But when I open it form test summary split it does not cut text when I scroll:
<img width="921" alt="image" src="https://user-images.githubusercontent.com/4973296/176277259-7beb96f2-8b08-403b-abd3-d7b8e83196f4.png">

**Comment by rcarriga** [comment]
Can you provide the file that the output is being read from? I can try reproduce with that

**Comment by rcarriga** [comment]
Is this still an issue?

**Comment by rcarriga** [comment]
I might be able to reproduce if you can provide the output file being read. It's the path in `neotest.Result.output`

**Comment by rouge8** [comment]
I'm having the same issue, can you explain how to find the path in `neotest.Result.output`?

**Comment by rcarriga** [comment]
Sorry that comment was directed at someone who knows the internals of neotest , hence the lack of instruction :sweat_smile: You can get it with a custom consumer:
```lua
neotest.setup({
  consumers = {
    print_output_path = function(client)
      client.listeners.results = vim.schedule_wrap(function(adapter_id, results)
        print(vim.inspect(results))
      end)
    end,
  },
...
```

I'd suggest just running a single test, that'll print out a lot of info if you run it on a suite.

Also note that the files are deleted when NeoVim exits, so you have to keep it open.

**Comment by rouge8** [comment]
Here's an output file from running a single test:

```
[1m================================================= test session starts ==================================================[0m
platform darwin -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
Using --randomly-seed=731529649
rootdir: /Users/andy/Dropbox/Projects/wanikani-burnt-kanji-to-anki, configfile: pyproject.toml
plugins: anyio-3.6.1, Faker-13.15.0, randomly-3.12.0, mock-3.8.2, cov-3.0.0, httpx-0.21.0
[1mcollecting ... [0m[1m
collected 1 item                                                                                                       [0m

tests/test_wanikani.py [32m.[0m[32m                                                                                         [100%][0m

[32m================================================== [32m[1m1 passed[0m[32m in 0.04s[0m[32m ===================================================[0m
```

The floating window cuts it off like so:

```
================================================= test session starts
platform darwin -- Python 3.10.5, pytest-7.1.2, pluggy-1.0.0
Using --randomly-seed=731529649
rootdir: /Users/andy/Dropbox/Projects/wanikani-burnt-kanji-to-anki, co
plugins: anyio-3.6.1, Faker-13.15.0, randomly-3.12.0, mock-3.8.2, cov-
collected 1 item

tests/test_wanikani.py .

================================================== 1 passed in 0.04s =
```

**Comment by rcarriga** [comment]
I'll need the binary data, copy/pasting into GitHub changes the contents unfortunately

**Comment by rouge8** [comment]
[7.zip](https://github.com/nvim-neotest/neotest/files/9185436/7.zip)

This should work then

**Comment by rcarriga** [comment]
Thanks! I can't reproduce with it however. My first thought is that it could be a NeoVim terminal bug. What version of NeoVim are you using?

**Comment by rcarriga** [comment]
Just to update here, I've tried running on 0.7.2 but still can't reproduce unfortunately. Not sure if there's much more that I can do, especially as it looks like a Neovim core bug. You could try testing with nightly to see if that works? Or perhaps a different install method (app image vs build from source etc)

**Comment by rouge8** [comment]
Hmm, I see the same cutting off behavior on the latest nightly nvim:

```
NVIM v0.8.0-dev-762-g0a049c322
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

**Comment by rcarriga** [comment]
OK I finally encountered this and figured out it's because of how NeoVim internally decides to truncate terminal lines. I've implemented a workaround so this should no longer happen

**Comment by rouge8** [comment]
Hmm, I'm still seeing the same cutting off behavior on a3229e979980c8b78e12ab9741e8c41390643b37.

```
NVIM v0.7.2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@HMBRW-A-001-M1-004.local
```

**Comment by rcarriga** [comment]
I hadn't fixed it for attaching, can you confirm if you still have the issue with opening output of an already completed test?

**Comment by rouge8** [comment]
On 2a887fe9b2ae604dac9715261355b75b67323dc0, I run the test, call `neotest.output.open`, and it's still cut off. 😞 Tested on 0.7.2 and v0.8.0-dev-1020-gea10e0c10...

**Comment by rcarriga** [comment]
Yeah I'm a bit stumped here, as far I can tell there's something weird going on in Neovim core with the terminal and I've no idea if it can be worked around. It seems like both of you are on MacOS so maybe it's something to do with that? Since I can't reproduce, I can't raise an issue in Neovim that would be of any use but if you want you can try to reproduce by separating out the output code in https://github.com/nvim-neotest/neotest/blob/master/lua/neotest/consumers/output.lua. It's pretty simple (just has a bit of fluff around handling custom open functions and closing) so it should be relatively simple to make it work with reading a file like the one you supplied

**Comment by sidlatau** [comment]
I am unable to reproduce this issue for a while, so closing it.
