### ISSUE TITLE
Feature request: Jest runner

### ISSUE THREAD

**Issue by khanghoang** [nvim-neotest/neotest#5]
Found you on [reddit](https://www.reddit.com/r/neovim/comments/v6a8ub/neotest_a_modern_powerful_testing_plugin/). Thanks a lot for working on this.

I'm a big fan of testing and debugging, too. I've played around with [similar plugin](https://github.com/khanghoang/coc-jest) but you take it to a different level.

I want to make Jest runner and I probably need some helps. Would you mind helping me along the way?

**Comment by rcarriga** [comment]
Yep absolutely happy to help :smile: Jest is likely to be a very popular runner so I'd be delighted to have someone take it on! My javascript is pretty rusty so hopefully most of your issues are in Lua land.

**Comment by haydenmeade** [comment]
I have written (badly) a jest plugin that works for my use cases 
https://github.com/haydenmeade/neotest-jest

**Comment by khanghoang** [comment]
This is great. I will definitely check your code later.

**Comment by mikaoelitiana** [comment]
I have tried using Neotest with jest and the adapter but I get an output `No tests found`. I have already run `TSInstall typescript` and `TSInstall javascript` but did not fixed my issue

**Comment by haydenmeade** [comment]
Do you have a sample of what your test file looks like?
Describe...
  It(...

Bit hard to help if I don't have some more info

**Comment by rcarriga** [comment]
I'm going to close this issue as there is an actively developed solution. Any issues with the adapter should be opened there
