### ISSUE TITLE
Feature request: Show output for running, in-progress tests

### ISSUE THREAD

**Issue by wookayin** [nvim-neotest/neotest#50]
The output window that would show the output of the test runner won't be available until the test has completed running. Therefore we cannot see outputs for a test that is running (for quite a long time): "No output for test_xxxxx".

It'd be great if there is a way to see the progress, or some intermediate outputs *streamed* in the terminal for tests that are still running and in progress.

**Comment by rcarriga** [comment]
Use `:h neotest.run.attach()`to see the output of the process as it runs

**Comment by wookayin** [comment]
I see! If I want to dispatch to either `neotest.run.attach` or `neotest.summary.open` depending the status of a test case (whether it's running or status), I'll need to have a programmatic API. How to get the (current) test object on the cursor or access its status (or other fields) programatically?

**Comment by rcarriga** [comment]
You'll have to create a custom consumer. I've just added some small docs `neotest.consumers` but the best examples will be the existing consumers. It'll also require using the plenary async library.

**Comment by rcarriga** [comment]
Closing this as the plugin allows for the desired behaviour

**Comment by wookayin** [comment]
I still think this is worth adding as a built-in component because it would be universally useful (either show the progress if in progress, or open the result if completed).

This is how I ended up adding my own custom consumers, following the suggestion:

```lua

neotest.setup {
  ...
  -- Add custom consumers on your own
  consumers = {
    attach_or_output = M.custom_consumers.attach_or_output(),
  },
}

function M.custom_consumers.attach_or_output()
  local self = { name = "attach_or_output" }
  local neotest = require("neotest")

  ---@type neotest.Client
  local client = nil

  self = setmetatable(self, {
    __call = function(_, client_)
      client = client_
      return self
    end,
  })

  -- neotest.attach_or_run.open()
  function self.open(args)
    args = args or {}
    local pos = neotest.run.get_tree_from_args(args)
    if pos and client:is_running(pos:data().id) then
      neotest.run.attach()
    else
      neotest.output.open()
    end
  end

  return self
end

```

Usage example:

```
command! -nargs=0 NeotestOutput    lua require("neotest").attach_or_output.open()
```
