### ISSUE TITLE
summary short output focus on floating window

### ISSUE THREAD

**Issue by xavier-balesi** [nvim-neotest/neotest#52]
from the summary window:
- 'o' mapping open full test output and keep focus on summary and hide floating output window on move
- if type 'O' mapping I expect to close the full test output then open the short but it's focus on the full output floating window

TY for this plugin !

**Comment by rcarriga** [comment]
You should now see the desired behaviour :smile:

**Comment by xavier-balesi** [comment]
Wonderful ! 
Thank you !
