### ISSUE TITLE
Setting up virtual text for diagnostics

### ISSUE THREAD

**Issue by hahuang65** [nvim-neotest/neotest#58]
It wasn't super clear what needs to be done for this.

I tried to `vim.diagnostics.config({ neotest = true })` but that didn't actually end up showing failures in the virtual text...

**Comment by rcarriga** [comment]
`:h vim.diagnostics.config()` describes how to configure diagnostics and namespaces. Use `nvim_create_namespace` to get the neotest namespace.
```lua
  vim.diagnostic.config({
    ...
  }, vim.api.nvim_create_namespace("neotest"))
```
