### ISSUE TITLE
Incorrect tree hierarchy when a directory and file have the same name

### ISSUE THREAD

**Issue by Bahex** [nvim-neotest/neotest#62]
When a file and a directory within the same directory have the same name(excluding the file's extension) neotest flattens the tree.

With this file tree:
```
src
├── mod_a
│   ├── mod_b
│   │   └── mod_c.rs
│   └── mod_b.rs
└── mod_a.rs
```
Summary window looks like this:
```
╰╮  src
 ├─  mod_a
 ├─  mod_a.rs
 ├─  mod_b
 ├─  mod_b.rs
 ╰─  mod_c.rs
```
When it should look like this:
```
╰╮ src
 ├╮ mod_a
 │├╮ mod_b
 ││╰─ mod_c.rs
 │╰─ mod_b.rs
 ╰─ mod_a.rs
```

The issue isn't just in the summary window, return values of `:parent()` nodes also have the same flattened structure.

**Comment by rcarriga** [comment]
Thanks for the report! This should now be working in latest master :smile:

**Comment by Bahex** [comment]
Works as expected 👍 thank you!
