### ISSUE TITLE
Feature Request - Cut the summary tree

### ISSUE THREAD

**Issue by weilbith** [nvim-neotest/neotest#63]
Hi ✌

I'm still in the progress of switching from `vim-ultest`. And I'm wondering if you could add any options for the summary provider to get a more lean output. Having the full directory tree is a bit too much for me. I already have a file tree on the left side and open files are highlighted etc. Having the whole tree in the summary window also needs so much more horizontal space. The test names/descriptions sometimes (depending on the project) start after 15 empty characters, leading to many lines being wrapped, or if wrapping is disabled most of it is hidden. 

I liked the old summary. But I see your aim to improve here with a new concept. Do you think there is a middle ground?

Thanks in advance!

**Comment by rcarriga** [comment]
I've added the ability to target positions so that the summary window will only render from the targetted position. There's a new `target` mapping and `neotest.summary.target` for setting it outside of the summary window.

**Comment by weilbith** [comment]
First of all, thank you very much for addressing this! 🙏🏾 
But I'm afraid I don't understand this feature. I don't even know what string I should set. 🙈 
Could you maybe give an example how to use this?

**Comment by rcarriga** [comment]
Sorry for not being clear, the main usage of this will be using the `toggle` mapping for the summary. Select a position in the summary tree and press `t` to target that position. Then only children of that position will be shown. You can use the `clear_toggle` mapping to then reset the target (default is `T`).

**Comment by weilbith** [comment]
Oh okay. Interesting. I'll give it a try. Thank you. 👍🏾
