### ISSUE TITLE
Feature Request: List running processes

### ISSUE THREAD

**Issue by justusschock** [nvim-neotest/neotest#66]
To stop a test process, sometimes you need to know the ID. Especially when running multiple test processes and you want to stop a specific one.

It would be nice, to have a list of currently running processes with their respective ID.
Ideally, when calling `neotest.run.stop({interactive=True})` or something similar it will do the following:

- If there is only one process, just stop it
- If there are multiple processes, select which one to stop

**Comment by rcarriga** [comment]
I've added in a client method to get running processes and the run consumer now has an `interactive` option for attach and stop. It won't automatically select the process if there's only one, but it uses vim.ui.select and you can customise it to do that.
