### ISSUE TITLE
Test reports using neotest-vim-test with rust give false positives

### ISSUE THREAD

**Issue by tomhampshire** [nvim-neotest/neotest#72]
Running: `lua require("neotest").run.run(vim.fn.expand("%"))` on a rust source code file shows both false positives and false negatives.

A minimal test file is below. In this example, the function, and the test, both produce a "tick" (the `silly_test` test should fail). 
The neotest test output shows that no tests have been run, however, running with vim-test's `TestFile` correctly runs the tests and shows the failed test.

```
fn silly_function() {}

#[cfg(test)]
mod tests {

    #[test]
    fn silly_test() {
        assert!(false);
    }
}

```

**Comment by rouge8** [comment]
I wrote a [Rust plugin](https://github.com/rouge8/neotest-rust) using [cargo-nextest](https://nexte.st/). That should fix your issue!

**Comment by tomhampshire** [comment]
Awesome, thanks. I'm running it now and it's doing the job great!

**Comment by rcarriga** [comment]
For other people that could see this, it should be working now. Issue was that vim-test uses relative paths whereas neotest uses absolute paths.
