### ISSUE TITLE
[BUG] Pytest: extra_args are not cleared on subsequent runs

### ISSUE THREAD

**Issue by WilsonCheng118** [nvim-neotest/neotest#88]
After calling `run()` with `extra_args`,
subsequent `run()` are called with an appended list of extra_args.

```lua
require('neotest').run.run({ vim.fn.getcwd(), extra_args = { "-v" } })
require('neotest').run.run(vim.fn.getcwd())
```
Both calls have output where -v flag is set.

Then make a new call with new extra_args:
```lua
require('neotest').run.run({ vim.fn.getcwd(), extra_args = { "-k core" } })
```
Output shows both `-v` and `-k core` are still being applied.

Running with neotest-python installed.

**Comment by rcarriga** [comment]
The bug report template exists for a reason. Please provide the log file and an init.lua to reproduce. I can't reproduce myself.
