### ISSUE TITLE
[BUG] Running colorscheme after running setup removes highlight information.

### ISSUE THREAD

**Issue by yuki-yano** [nvim-neotest/neotest#91]
**NeoVim Version**
$ nvim --version
NVIM v0.8.0-dev-2317-g5e98a4187
Build type: Release
LuaJIT 2.1.0-beta3

**Describe the bug**

After setup in init.vim, setting colorschema will remove highlight
I think it is correct to execute the following code in the ColorSchema event as well
https://github.com/nvim-neotest/neotest/blob/d018868c1abe79bf730c9acbbcdaa58ebec8d1f4/lua/neotest/config/init.lua#L3-L20

**To Reproduce**

```vim
call plug#begin('~/.vim/plugged')
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-treesitter/nvim-treesitter'
Plug 'antoinemadec/FixCursorHold.nvim'
Plug 'nvim-neotest/neotest'
Plug 'haydenmeade/neotest-jest'
call plug#end()

lua << EOF
require("neotest").setup({
  adapters = {
    require("neotest-jest")
  }
})
EOF
```

- Open jest test file
- Run `lua require('neotest').summary.open()`.
- Run `colorscheme blue`.
- neotest's highlight is removed

**Expected behavior**

Highlight is reconfigured when running colorscheme.

**Comment by rcarriga** [comment]
This should be working as expected in master :smile:
