### ISSUE TITLE
[BUG] Jest: parametrised tests giving incorrect output and icon

### ISSUE THREAD

**Issue by prudnikovsv** [nvim-neotest/neotest#97]
**NeoVim Version**
NVIM v0.8.0-dev-827-gb6a963bde

**Describe the bug**
When running jest parametrised tests as run whole file, plugin marks passed tests as failed, see:
![image](https://user-images.githubusercontent.com/8155269/185906984-d4c98485-0b9a-4245-9553-2471c1c0fdf3.png)
When output is saying that they passed, see:
![Screenshot 2022-08-22 at 12 08 18](https://user-images.githubusercontent.com/8155269/185907300-92bd9c2d-2ea1-4ecc-8529-767353c58c65.png)

As well as, when running plugin with "run nearest test" adn test is parametrised, I get same error state, and on top of that 0 output, see:
![image](https://user-images.githubusercontent.com/8155269/185907819-f477b31c-5617-4188-a53a-feed95d68500.png)

**To Reproduce**
Configuration:
```lua
my.nnoremap("<leader>tt", ":lua require('neotest').run.stop()<CR>")
my.nnoremap("<leader>tn", ":lua require('neotest').run.run()<CR>")
my.nnoremap("<leader>td", ":lua require('neotest').run.run({ strategy = 'dap'})<CR>")
my.nnoremap("<leader>tf", ":lua require('neotest').run.run(vim.fn.expand('%'))<CR>")

my.nnoremap("<leader>ts", ":lua require('neotest').summary.toggle()<CR>")
my.nnoremap("<leader>to", ":lua require('neotest').output.open()<CR>")

require("neotest").setup({
	adapters = {
		require("neotest-jest"),
	},
	output = {
		enable = true,
		open_on_run = true,
	},
})
```

You can edit the following example file to include your adapters and other required setup.
```lua
-- install packer

packer.startup(function(use)
  ...
  	use({
			"nvim-neotest/neotest",
			requires = {
				"nvim-lua/plenary.nvim",
				"nvim-treesitter/nvim-treesitter",
				"antoinemadec/FixCursorHold.nvim",
				"haydenmeade/neotest-jest",
			},
		})
 ...
```

* Create parameterized test with file extension TS
* Go to test file
* Simply run test using plugin

**Comment by rcarriga** [comment]
This is a neotest-jest issue https://github.com/haydenmeade/neotest-jest/issues/2
